### PR TITLE
Create the base.html template with base.css

### PR DESCRIPTION
**Pull request by freddie-nelson**
Created the base template and put the navbar in too

please review and merge if approved 👍

### CODE REVIEW

**Comment by Fraser-Levack** [comment]
## This looks great I vote rebase and merge !

#🦈

**Comment by freddie-nelson** [comment]
is this all good to merge?

**Comment by ScottGlidden** [comment]
CSS looks fantastic! 

However it seems to have broken the sign-up system (can't find a way to sign up anymore), and logging in now redirects to a blank page if failed login. If these are intended side effects, looks good :)

**Comment by freddie-nelson** [comment]
> CSS looks fantastic!
> 
> However it seems to have broken the sign-up system (can't find a way to sign up anymore), and logging in now redirects to a blank page if failed login. If these are intended side effects, looks good :)

yeah all will be fixed when i do the sign up and login pages

**Pull request merged**
