### PR TITLE
Feat : Added Likes/dislikes

### PR DESCRIPTION
**Pull request by Fraser-Levack**
### Added Likes and Dislikes on tune searches and within profile when updated.

### CODE REVIEW

**Review by freddie-nelson — COMMENTED** [review]
Cant clone and review right now but only thing I'm seeing is the JS folder should he lower case just to stick with better folder naming conventions. And maybe the use of jquery could be avoided as it's really outdated now. I could take a look tomorrow if you like

**Comment by Fraser-Levack** [comment]
Cool thx Freddie. Yes I'm still new to conventions unfortunately. I think the only reason jQuery is used is due to old Rango methods.

**Comment by freddie-nelson** [comment]
Yeah no problem fraser I'd be happy to merge anyway

**Comment by Fraser-Levack** [comment]
Fixed name of JS   </br>    :)

**Comment by freddie-nelson** [comment]
Hey fraser just had a chance to clone this now and I found a couple of things.

It seems you can like and dislike a tune whereas I believe the intended implementation was to only be able to like tunes and unlike them?

You can also keep liking and disliking a tune multiple times as well as disliking a tune until it has negative likes.

In #25 I've implemented a system using local storage to fake the likes and unliking which we could hook up with the server side logic you've implemented here?

I think we just need to make a like/unlike view instead of the like and dislike there is currently.

**Comment by freddie-nelson** [comment]
Hey @Fraser-Levack I've made some changes and the liking/unliking should match the spec now.

We can get this merged then I can integrate with the profile page and tune player I created in #25

**Review by freddie-nelson — APPROVED** [review]

**Comment by Fraser-Levack** [comment]
Thx a bunch bro

**Pull request merged**
